/**
 * Type definitions generated from the Oxid scripting API metadata.
 * Do not edit this file manually.
 */

declare module "oxid/core" {
  /** Core application features and the entity lifecycle. */
  /**
   * Base class for Oxid script entities.
   */
  export class Entity {
    constructor();
  }

}

declare module "oxid/math" {
  /** 2D mathematical types and utilities. */
  /**
   * Mutable 2D vector with x and y components.
   */
  export class Vector2D {
    constructor(x: number, y: number);
    x: number;
    y: number;
  }

}

declare module "oxid/color" {
  /** Types for representing RGBA colors. */
  /**
   * Mutable RGBA color.
   */
  export class Color {
    constructor(r: number, g: number, b: number, a: number);
    r: number;
    g: number;
    b: number;
    a: number;
  }

}

declare module "oxid/shapes" {
  import type { Vector2D } from "oxid/math";
  import type { Color } from "oxid/color";
  /**
   * Draws an arc on the screen.
   * @param position Arc position.
   * @param sides Resolution used to approximate the curve; higher values produce a smoother arc.
   * @param radius Arc radius.
   * @param rotation Initial rotation in degrees.
   * @param thickness Espessura do arco.
   * @param arc Abertura do arco em graus.
   * @param color Color used for drawing.
   */
  export function drawArc(position: Vector2D, sides: number, radius: number, rotation: number, thickness: number, arc: number, color: Color): void;

  /**
   * Draws a circle on the screen.
   * @param x Horizontal position.
   * @param y Vertical position.
   * @param radius Circle radius.
   * @param color Color used for drawing.
   */
  export function drawCircle(x: number, y: number, radius: number, color: Color): void;

  /**
   * Draws a rectangle on the screen.
   * @param x Horizontal position.
   * @param y Vertical position.
   * @param width Rectangle width.
   * @param height Rectangle height.
   * @param color Color used for drawing.
   */
  export function drawRectangle(x: number, y: number, width: number, height: number, color: Color): void;

  /**
   * Draws a line between two points.
   * @param start Starting point of the line.
   * @param end Ending point of the line.
   * @param thickness Line thickness.
   * @param color Color used for drawing.
   */
  export function drawLine(start: Vector2D, end: Vector2D, thickness: number, color: Color): void;

  /**
   * Draws the outline of a triangle.
   * @param v1 First vertex.
   * @param v2 Second vertex.
   * @param v3 Third vertex.
   * @param thickness Line thickness.
   * @param color Color used for drawing.
   */
  export function drawTriangleLines(v1: Vector2D, v2: Vector2D, v3: Vector2D, thickness: number, color: Color): void;

  /**
   * Draws the outline of a regular polygon.
   * @param position Center position of the polygon.
   * @param sides Number of polygon sides.
   * @param radius Distance from the center to each vertex.
   * @param rotation Polygon rotation in degrees.
   * @param thickness Line thickness.
   * @param color Color used for drawing.
   */
  export function drawPolygonLines(position: Vector2D, sides: number, radius: number, rotation: number, thickness: number, color: Color): void;

}

declare module "oxid/input" {
  import type { Vector2D } from "oxid/math";
  /**
   * Returns true while the key is held down.
   * @param key Key name. Case-insensitive; spaces, '_' and '-' are ignored. Examples: "A", "ArrowLeft", "Space", "Enter", "Escape", "LeftShift", "F1".
   */
  export function isKeyDown(key: string): boolean;

  /**
   * Returns true only during the frame when the key was pressed.
   * @param key Key name. Case-insensitive; spaces, '_' and '-' are ignored. Examples: "A", "ArrowLeft", "Space", "Enter", "Escape", "LeftShift", "F1".
   */
  export function isKeyPressed(key: string): boolean;

  /**
   * Returns true only during the frame when the key was released.
   * @param key Key name. Case-insensitive; spaces, '_' and '-' are ignored. Examples: "A", "ArrowLeft", "Space", "Enter", "Escape", "LeftShift", "F1".
   */
  export function isKeyReleased(key: string): boolean;

  /**
   * Returns the current mouse position in screen coordinates.
   */
  export function mousePosition(): Vector2D;

  /**
   * Returns true while the mouse button is held down.
   * @param button Mouse button name. Accepted values: "left", "middle", and "right".
   */
  export function isMouseButtonDown(button: string): boolean;

  /**
   * Returns true only during the frame when the mouse button was pressed.
   * @param button Mouse button name. Accepted values: "left", "middle", and "right".
   */
  export function isMouseButtonPressed(button: string): boolean;

  /**
   * Returns true only during the frame when the mouse button was released.
   * @param button Mouse button name. Accepted values: "left", "middle", and "right".
   */
  export function isMouseButtonReleased(button: string): boolean;

}

declare module "oxid/text" {
  /** 2D text rendering and measurement. */
  import type { Vector2D } from "oxid/math";
  import type { Color } from "oxid/color";

  /**
   * Metrics calculated for a single line of text.
   */
  export class TextMetrics {
    constructor(width: number, height: number, offsetY: number);
    readonly width: number;
    readonly height: number;
    readonly offset_y: number;
  }

  /**
   * Draws 2D text on the screen. The y coordinate represents the text baseline.
   * @param text Text content to draw.
   * @param position Text position in screen coordinates.
   * @param fontSize Tamanho da fonte em pixels. Deve ser maior que zero.
   * @param color Color used for the text.
   */
  export function drawText(text: string, position: Vector2D, fontSize: number, color: Color): void;

  /**
   * Draws multiline text using '\n' as the separator. The y coordinate represents the first line baseline.
   * @param text Text content to draw.
   * @param position Initial text block position in screen coordinates.
   * @param fontSize Tamanho da fonte em pixels. Deve ser maior que zero.
   * @param color Color used for the text.
   * @param lineDistance Line spacing multiplier. Use 1.0 for default spacing.
   */
  export function drawMultilineText(text: string, position: Vector2D, fontSize: number, color: Color, lineDistance?: number): void;

  /**
   * Measures a single line of text using the default font and returns its width, height, and offset_y.
   * @param text Text content to measure.
   * @param fontSize Tamanho da fonte em pixels. Deve ser maior que zero.
   */
  export function measureText(text: string, fontSize: number): TextMetrics;

}

declare module "oxid/texture" {
  /** Carregamento e desenho de texturas 2D. */
  import type { Vector2D } from "oxid/math";

  /**
   * Texture loaded by the runtime with dimensions and source path.
   */
  export class Texture2D {
    readonly path: string;
    readonly width: number;
    readonly height: number;
  }

  /**
   * Loads a texture from disk and returns a reusable Texture2D object.
   * @param path Texture file path. Relative paths use the current working directory.
   */
  export function loadTexture(path: string): Texture2D;

  /**
   * Draws a texture using its original size.
   * @param texture Texture returned by loadTexture.
   * @param position Top-left position in screen coordinates.
   */
  export function drawTexture(texture: Texture2D, position: Vector2D): void;

  /**
   * Draws a resized texture with optional rotation in radians.
   * @param texture Texture returned by loadTexture.
   * @param position Top-left position in screen coordinates.
   * @param size Destination width and height for the texture.
   * @param rotation Rotation in radians. Defaults to 0 when omitted.
   */
  export function drawTextureScaled(texture: Texture2D, position: Vector2D, size: Vector2D, rotation?: number): void;

}

