/**
 * Type definitions generated from the Oxid scripting API metadata.
 * Do not edit this file manually.
 */

declare module "oxid/core" {
  /** Core da aplicação e ciclo de vida de entidades. */
  /**
   * Classe base do padrão de scripting do Oxid.
   */
  export class Entity {
    constructor();
  }
}

declare module "oxid/math" {
  /** Tipos e utilitários matemáticos 2D. */
  /**
   * Vetor 2D mutável com componentes x e y.
   * @param x Componente horizontal.
   * @param y Componente vertical.
   */
  export class Vector2D {
    constructor(x: number, y: number);
    x: number;
    y: number;
  }
}

declare module "oxid/color" {
  /** Tipos para representar cores RGBA. */
  /**
   * Cor RGBA mutável.
   * @param r Componente vermelho.
   * @param g Componente verde.
   * @param b Componente azul.
   * @param a Componente alfa.
   */
  export class Color {
    constructor(r: number, g: number, b: number, a: number);
    r: number;
    g: number;
    b: number;
    a: number;
  }
}

declare module "oxid/shapes" {
  import type { Vector2D } from "oxid/math";
  import type { Color } from "oxid/color";

  /**
   * Desenha um arco.
   * @param position Posição do arco em coordenadas de tela.
   * @param sides Quantidade de lados usados para aproximar o arco.
   * @param radius Raio do arco.
   * @param rotation Rotação do arco em graus.
   * @param thickness Espessura do arco.
   * @param arc Extensão angular do arco em graus.
   * @param color Cor usada no desenho.
   */
  export function drawArc(position: Vector2D, sides: number, radius: number, rotation: number, thickness: number, arc: number, color: Color): void;

  /**
   * Desenha um círculo.
   * @param x Coordenada horizontal.
   * @param y Coordenada vertical.
   * @param radius Raio do círculo.
   * @param color Cor usada no desenho.
   */
  export function drawCircle(x: number, y: number, radius: number, color: Color): void;

  /**
   * Desenha um retângulo.
   * @param x Coordenada horizontal.
   * @param y Coordenada vertical.
   * @param width Largura do retângulo.
   * @param height Altura do retângulo.
   * @param color Cor usada no desenho.
   */
  export function drawRectangle(x: number, y: number, width: number, height: number, color: Color): void;
}

declare module "oxid/input" {
  import type { Vector2D } from "oxid/math";

  /**
   * Retorna true enquanto a tecla estiver pressionada.
   * @param key Nome da tecla ou alias aceito pelo parser de input.
   */
  export function isKeyDown(key: string): boolean;

  /**
   * Retorna true apenas no frame em que a tecla foi pressionada.
   * @param key Nome da tecla ou alias aceito pelo parser de input.
   */
  export function isKeyPressed(key: string): boolean;

  /**
   * Retorna true apenas no frame em que a tecla foi solta.
   * @param key Nome da tecla ou alias aceito pelo parser de input.
   */
  export function isKeyReleased(key: string): boolean;

  /** Retorna a posição atual do mouse em coordenadas de tela. */
  export function mousePosition(): Vector2D;

  /**
   * Retorna true enquanto o botão do mouse estiver pressionado.
   * @param button Nome ou alias do botão do mouse.
   */
  export function isMouseButtonDown(button: string): boolean;

  /**
   * Retorna true apenas no frame em que o botão do mouse foi pressionado.
   * @param button Nome ou alias do botão do mouse.
   */
  export function isMouseButtonPressed(button: string): boolean;

  /**
   * Retorna true apenas no frame em que o botão do mouse foi solto.
   * @param button Nome ou alias do botão do mouse.
   */
  export function isMouseButtonReleased(button: string): boolean;
}

declare module "oxid/text" {
  import type { Vector2D } from "oxid/math";
  import type { Color } from "oxid/color";

  /** Renderização e medição de texto 2D. */
  /**
   * Métricas calculadas para uma linha de texto.
   * @param width Largura do texto.
   * @param height Altura do texto.
   * @param offsetY Offset vertical da métrica.
   */
  export class TextMetrics {
    constructor(width: number, height: number, offsetY: number);
    readonly width: number;
    readonly height: number;
    readonly offset_y: number;
  }

  /**
   * Desenha texto 2D na tela. A coordenada y representa a baseline do texto.
   * @param text Conteúdo textual a ser desenhado.
   * @param position Posição do texto em coordenadas de tela.
   * @param fontSize Tamanho da fonte em pixels. Deve ser maior que zero.
   * @param color Cor usada no texto.
   */
  export function drawText(text: string, position: Vector2D, fontSize: number, color: Color): void;

  /**
   * Desenha texto multilinha usando '\n' como separador. A coordenada y representa a baseline da primeira linha.
   * @param text Conteúdo textual a ser desenhado.
   * @param position Posição inicial do bloco de texto em coordenadas de tela.
   * @param fontSize Tamanho da fonte em pixels. Deve ser maior que zero.
   * @param color Cor usada no texto.
   * @param lineDistance Multiplicador de distância entre linhas. Use 1.0 para o espaçamento padrão.
   */
  export function drawMultilineText(text: string, position: Vector2D, fontSize: number, color: Color, lineDistance?: number): void;

  /**
   * Mede um texto de linha única usando a fonte padrão e retorna largura, altura e offset_y.
   * @param text Conteúdo textual a ser medido.
   * @param fontSize Tamanho da fonte em pixels.
   */
  export function measureText(text: string, fontSize: number): TextMetrics;
}

declare module "oxid/texture" {
  import type { Vector2D } from "oxid/math";

  /** Carregamento e desenho de texturas 2D. */
  /**
   * Textura carregada pelo runtime com dimensões e caminho de origem.
   */
  export class Texture2D {
    readonly path: string;
    readonly width: number;
    readonly height: number;
  }

  /**
   * Carrega uma textura do disco e retorna um objeto Texture2D reutilizável.
   * @param path Caminho do arquivo de textura. Caminhos relativos usam o diretório de trabalho atual.
   */
  export function loadTexture(path: string): Texture2D;

  /**
   * Desenha uma textura usando seu tamanho original.
   * @param texture Textura retornada por loadTexture.
   * @param position Posição do canto superior esquerdo em coordenadas de tela.
   */
  export function drawTexture(texture: Texture2D, position: Vector2D): void;

  /**
   * Desenha uma textura redimensionada, com rotação opcional em radianos.
   * @param texture Textura retornada por loadTexture.
   * @param position Posição do canto superior esquerdo em coordenadas de tela.
   * @param size Largura e altura de destino da textura.
   * @param rotation Rotação em radianos. Quando omitido, usa 0.
   */
  export function drawTextureScaled(texture: Texture2D, position: Vector2D, size: Vector2D, rotation?: number): void;
}
